export const TRUSTED_NEWS_SOURCES = [
  {
    name: "PIB India Agriculture",
    type: "rss",
    url: "https://pib.gov.in/RssMain.aspx?ModId=6&Lang=1&Regid=3",
    category: "government",
    trusted: true,
  },
  {
    name: "BusinessLine Agri Business",
    type: "rss",
    url: "https://www.thehindubusinessline.com/economy/agri-business/feeder/default.rss",
    category: "market",
    trusted: true,
  },
  {
    name: "BusinessLine Commodities",
    type: "rss",
    url: "https://www.thehindubusinessline.com/markets/commodities/feeder/default.rss",
    category: "market",
    trusted: true,
  },
  {
    name: "Krishi Jagran",
    type: "rss",
    url: "https://krishijagran.com/feeds",
    category: "general",
    trusted: true,
  },
];

export const SUPPORTED_CROPS = [
  "Wheat",
  "Rice",
  "Cotton",
  "Groundnut",
  "Sugarcane",
  "Vegetables",
];

export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
];
